### ISSUE TITLE
Support for statamic login form

### ISSUE THREAD

**Issue by goellner** [aryehraber/statamic-captcha#17]
Is it possible to support the out of the box login form too? there is already a setting for the user registration form, but wanted to add it to my login form too.

**Comment by aryehraber** [comment]
Hey @goellner!  Nice suggestion, should be possible so will take a look when I next find some time. If you need this asap then a PR is most welcome 😊

**Comment by aryehraber** [comment]
This feature has been added to the latest release!

You'll need to add the new `user_login` config option to opt-in for Login verification ([see updated config here](https://github.com/aryehraber/statamic-captcha/blob/master/config/captcha.php#L9)).

Let me know if you run into any issues!

**Comment by skylennard** [comment]
@aryehraber I'm trying to get this to protect my email login form when I have oAuth enabled, but it doesn't seem to work...?

**Comment by aryehraber** [comment]
@skylennard I didn't test other login methods outside of [Statamic's standard login form](https://statamic.dev/tags/user-login_form#content). 

Can you verify that the standard way does work for you? If it does, then the issue is OAuth-specific and I can look at that more closely.
