### ISSUE TITLE
captcha:head stopped working with section

### ISSUE THREAD

**Issue by vitor-ao** [aryehraber/statamic-captcha#2]
After the last update (1.0.3), when entering the contact page I get the error **View [recaptcha.head] not found.**
Contact template:
```
{{ section:script }}
{{ captcha:head }}
{{ /section:script }}
...
```
Layout template:
```
<head>
  {{ partial:partials/head }}
  {{ yield:script }}
</head>
...
```

If the `captcha:head` is in the layout template, the problem does not occur.

**Comment by aryehraber** [comment]
Hi @vitor-ao, thanks for reporting this issue, I haven't tested the tag inside of Statamic's `section` tag, will have a look at this asap!

**Comment by aryehraber** [comment]
@vitor-ao Just gave this a quick try with latest version of Statamic 3 & current Captcha addon, and it seems to work fine. 

Can you confirm that you're on the latest Statamic version, and if so would you be able to recreate the issue in a fresh project and check again/send it over?

**Comment by vitor-ao** [comment]
Problem solved. Must have been remnants of the previous recaptcha beta that didn't removed completely. Eliminated the vendor folder and ran `composer install` and that fixed it.
