### ISSUE TITLE
Captcha blocks `EntrySaving` event from propagating

### ISSUE THREAD

**Issue by edalzell** [aryehraber/statamic-captcha#21]
Right now Captcha returns `$entry` and according to this code in `EntrySaving::dispatch`, the propagation stops on the first non-null value:

```php
    /**
     * Dispatch the event with the given arguments, and halt on first non-null listener response.
     *
     * @return mixed
     */
    public static function dispatch()
    {
        return event(new static(...func_get_args()), [], true);
    }
```

This means if you have additional listeners, they don't get called when you return anything.

Confirmed that this code in `handle` fixes the issue, in the CP:

```php
        if (Statamic::isCpRoute()) {
            return null;
        }
```

**Comment by aryehraber** [comment]
@edalzell Oh good find! Should we just stop returning the entry all together (outside of CP as well), don't think it's doing anything useful anyway?

**Comment by edalzell** [comment]
Yes return `null` so the propagation can continue. The return value is never used, for entries.

**Comment by aryehraber** [comment]
Version `1.5.2` has been released, thanks for your help on this!
