### ISSUE TITLE
Getting two recaptcha challenge divs before closing body tag if two forms on same page

### ISSUE THREAD

**Issue by twd3** [aryehraber/statamic-captcha#23]
I'm seeing two recaptcha challenge divs before closing body tag if two forms on same page. Specifically, I have a login form and a normal form. Not sure if it is happening with just two normal forms on same page. Also, it looks like the scripts in the head are NOT duplicating and are fine.

![1](https://user-images.githubusercontent.com/16004958/125372680-ed163600-e340-11eb-9ffd-2d35e8a08d80.png)

**Comment by twd3** [comment]
Hahaha, I think I'm being silly here and it needs two challenges because there is two forms on the page. Can you close this if this is how it's supposed to be?

**Comment by aryehraber** [comment]
Hey @twd3, yeah this sounds like expected behaviour — assuming each form works correctly with their respective captchas. 

Closing but feel free to re-open if you notice issues with the captchas themselves using multiple forms.
