### ISSUE TITLE
No badge showing and failing every submit

### ISSUE THREAD

**Issue by ewhicher** [aryehraber/statamic-captcha#25]
Hey!

I'm using ReCaptcha V2, composer updated to the latest everything, added the form handle and doubled checked it is correct,]. I've added the tag to the form markup, site key and secret to env (and tested in the config) and I have even dd'd to make sure it is actually registering the addon. Every time I just get `Captcha failed` 🤕

Side point I am not seeing the Badge...is this an indication of something?

Appreciate any help my man 🙂

**Comment by aryehraber** [comment]
Hey @ewhicher! Yeah it's not a good sign if the badge isn't showing... Hard to tell what could be going wrong without more details. Is there a test link or repo I can take a look at?

**Comment by ewhicher** [comment]
Thanks for the quick response @aryehraber, sorry for the delay - I got sick!

I've invited you to the repo, it is a one page site I popped on to {{S3}} for a friend so we could make the form more secure. Everything is on the live branch I believe.

I can add you to my Slack to have a proper catch up?

**Comment by aryehraber** [comment]
Hey @ewhicher, no worries! Hope you're feeling better!

Cool will accept the invite and try to have a look later this week. Will keep you posted!

**Comment by aryehraber** [comment]
@ewhicher Took a quick look after cloning the repo and it seems you're missing the ` {{ captcha:head }}` in the `head` section of your `layout.antlers.html` (see [Usage section](https://github.com/aryehraber/statamic-captcha#usage) in docs). 

After adding that tag + updating the Captcha config to protect the `contact` form, everything works locally as expected. Hope that helps!

**Comment by ewhicher** [comment]
Ah man can't believe I missed that. Thanks for taking a quick look, you da best!

Will test and get it live. Thank you 🙏

**Comment by aryehraber** [comment]
Great! Feel free to close the issue once you've confirmed it works. Glad I could help!
