### ISSUE TITLE
Error Message not localizable

### ISSUE THREAD

**Issue by fjahn** [aryehraber/statamic-captcha#28]
The `error_message` that is configurable via `captcha.php` is not localized. This could be fixed by wrapping all references to `config('captcha.error_message')` in a call to the function `__`. See [Laravel Localization docs](https://laravel.com/docs/8.x/localization) for details.

I can also do a PR in a couple of days if you say that it would be merged.

**Comment by aryehraber** [comment]
Hi Florian, a PR would be much appreciated. Thanks!

**Comment by aryehraber** [comment]
Thanks again @fjahn! This is now available in latest release 🚀
