### ISSUE TITLE
Undefined property: Statamic\Events\FormSubmitted::$submission

### ISSUE THREAD

**Issue by curtisblackwell** [aryehraber/statamic-captcha#3]
When submitting my form, I get this exception. [Here it is on Flare.](https://flareapp.io/share/4m43ap5M#F58)

`$event`'s only property is `form`. I know to get the form's handle, you can do this: `$event->form->form->handle()`, but I don't know what the value of `$submission` is supposed to be, so I can't submit a PR to fix.

**Comment by aryehraber** [comment]
@curtisblackwell Hmm, what version of Statamic are you on? As of [v3.0.1](https://github.com/statamic/cms/releases/tag/v3.0.1) they added a `submission` property.

**Comment by curtisblackwell** [comment]
Ah, yep. Forgot I wasn't on the latest version. Thanks Aryeh!
