### ISSUE TITLE
Config Can't use secret key from .env

### ISSUE THREAD

**Issue by enespolat24** [aryehraber/statamic-captcha#33]
Hi, we encountered an issue. It seems config file can't use the secret key we define in the .env. Can you check it ?

**Comment by aryehraber** [comment]
Hi @enespolat24, could you please supply some more details:

- Statamic version
- Captcha version
- Copy of `captcha` config file (please remove sensitive data)
- Copy of `.env` file (please remove sensitive data)

Thanks!

**Comment by enespolat24** [comment]
statamic 3.2.32
captcha v2


this is my config file 
```php
<?php

return [
    'service' => 'Recaptcha', // options: Recaptcha / Hcaptcha
    'sitekey' => env('CAPTCHA_SITEKEY', ''),
    'secret' => env('CAPTCHA_SECRET', ''),
    'collections' => [],
    'forms' => ['contact],
    'user_login' => false,
    'user_registration' => false,
    'disclaimer' => '',
    'invisible' => true,
    'hide_badge' => false,
    'enable_api_routes' => false,
];
```
this is my .env 
```
CAPTCHA_SITEKEY=blablabalbalb
CAPTCHA_SECRETKEY=blablalbalbalbal
```

**Comment by aryehraber** [comment]
Thanks for the quick reply! 

I think I see the issue, the `.env` key `CAPTCHA_SECRETKEY` should be `CAPTCHA_SECRET`. Does that solve the issue?

**Comment by enespolat24** [comment]
Yeah that fixed my issue. It would be great to add this in the documentation. cause i couldn't find it. because i didn't know it was `CAPTCHA_SECRET`. Thank you so much !! 🚀

**Comment by aryehraber** [comment]
The key `CAPTCHA_SECRET` is right there in the config file you shared, so don't think it's needed in the docs. 

Glad everything is working now 👍
