### ISSUE TITLE
Not verifying passed solutions

### ISSUE THREAD

**Issue by JacobTinston** [aryehraber/statamic-captcha#39]
In my reCaptcha admin console, I get this warning on a site that uses this plugin:

`We detected that your site is verifying reCAPTCHA passed solutions less than 50% of the time. This could indicate a problem with your integration with reCAPTCHA. Please see [our developer site](https://developers.google.com/recaptcha/docs/verify#api-request) for more information.`

**Comment by aryehraber** [comment]
Hi @JacobTinston, hard to debug with more info. Have you verified that the Captcha Addon has been [installed](https://github.com/aryehraber/statamic-captcha#installation) correctly (including adding your forms in the config file)?

**Comment by JacobTinston** [comment]
Hi, yeah I haven't really got any more info to give, that's the only thing I've got from captcha. I've updated to the latest version, added both `captcha:head' and 'captcha' tags, I've got all my forms with the correct handles in the config file and have the correct site/secret keys in the env so not really sure. Sorry I can't be more helpful!

**Comment by aryehraber** [comment]
Hmm, sounds like you've set things up correctly...  I've not seen/heard of this particular error message before, so not sure what to suggest as follow up steps to debug further. 

Assuming the config is setup correctly, users shouldn't be able to submit the form(s) without a solved captcha, so I don't know how less than 50% of forms are being submitted without being verified.

Are you doing anything special with ajax, or just submitting the forms the "normal" way in Statamic?

**Comment by JacobTinston** [comment]
Nothing special, just the "statamic" way. I can see it does block a lot of spam, but some still does come through. I wonder if it's just that the majority of requests fail due to spam.

**Comment by aryehraber** [comment]
Ooh interesting, I hadn't interpreted the error message in that way... you might be right though, perhaps reCAPTCHA is blocking more spam than usual for this form (over 50% of submissions)?

Since I've not seen this error myself, nor received a GH issue before, I'm leaning towards that this isn't a problem within the Addon. What do you think?

**Comment by JacobTinston** [comment]
Yeah, I think you're right, just thought it was worth raising! Thanks for you help.

**Comment by aryehraber** [comment]
Ok cool. No problem, thank you for bringing this scenario to my attention 👍
