### ISSUE TITLE
Support for Cloudflare Turnstile

### ISSUE THREAD

**Issue by sjclark** [aryehraber/statamic-captcha#40]
Hey Aryeh! Just wondering if you had any intention of supporting Cloudflare Turnstile? 🙂
https://blog.cloudflare.com/turnstile-private-captcha-alternative/

**Comment by aryehraber** [comment]
Hi @sjclark, thanks for bringing this to my attention. Yeah, I'd love to add support for Turnstile 👍 Will try and take a closer look at integration docs soon.

**Comment by sjclark** [comment]
Beaten to it 😄 https://statamic.com/addons/stoffelio/cloudflare-turnstile

**Comment by aryehraber** [comment]
Haha, great to see the community move so fast!

This Captcha addon supports a few additional features, however, so I'll probably still add support when I have time. This will also allow existing Captcha users to easily switch over by simply updating a config option and API keys.

**Comment by aryehraber** [comment]
Just released v1.9.0 with Cloudflare Turnstile support. Enjoy!

**Comment by sjclark** [comment]
Wooooohooooooo! 🔥
