### ISSUE TITLE
Turnstile theme support

### ISSUE THREAD

**Issue by elmanvebs** [aryehraber/statamic-captcha#42]
Hi there,

Any plans for Turnstile theme selection support? 

```
auto, dark or light theme
````

**Comment by aryehraber** [comment]
Hi @elmanvebs, this is already possible by simply adding Turnstile's data attribute to the Captcha tag:

```
{{ captcha data-theme="dark" }}
```

It seems this feature is missing from the docs so I'll be sure to add a section highlighting it. Thanks for bringing it to my attention!
