### ISSUE TITLE
Setting Google ReCaptcha `data-size="compact"`

### ISSUE THREAD

**Issue by sjclark** [aryehraber/statamic-captcha#43]
😄 Is there any way to configure the **compact** display of google captcha - have site where it's overflowing on mobile....?

`data-size="compact"`

RE: https://developers.google.com/recaptcha/docs/display#render_param

![image](https://user-images.githubusercontent.com/4531017/201551418-5afa37c2-3d6a-4387-898a-509ed03d7e3e.png)

**Comment by sjclark** [comment]
Ignore me, I should really learn to read ❤️

**Comment by sjclark** [comment]
Actually maybe I spoke too soon.... I don't seem to be able to get the **specific data size** data atrribute to flow through.... anything I seem to be doing wrong below? (have cleared application, stache & static cache)

![Screen Shot 2022-11-14 at 11 07 48 am](https://user-images.githubusercontent.com/4531017/201551887-2c32a06a-7708-4c85-a7e4-4673f22fb95f.png)

![Screen Shot 2022-11-14 at 11 08 18 am](https://user-images.githubusercontent.com/4531017/201551889-a50b2502-d4fb-4c28-9b8b-e85e29420394.png)

![Screen Shot 2022-11-14 at 11 09 58 am](https://user-images.githubusercontent.com/4531017/201551973-3b593026-5832-4000-98d6-ebfab2179731.png)

**Comment by aryehraber** [comment]
Hi @sjclark, thanks for reporting this one -- there was a special case for `data-size` which stopped the attribute from merging into the rendered tag.

Just released `v1.9.1` which fixes this issue!

**Comment by sjclark** [comment]
Thanks! I can't even remember the site I was trying to implement this in now! 😂
