### ISSUE TITLE
Any way to make this work with AMP reCaptcha?

### ISSUE THREAD

**Issue by twd3** [aryehraber/statamic-captcha#6]
It would be so cool if this changed to an AMP captcha with the form was on an AMP version of the page. V3 now has that AMP feature. Here is AMP reCaptcha on GitHub: https://github.com/ampproject/amphtml/tree/master/extensions/amp-recaptcha-input

**Comment by twd3** [comment]
AMP is dead or dying so might want to reconsider even doing this.

**Comment by aryehraber** [comment]
Yeah, saw the AMP news come by recently so going to close 👍
